export const STATIONS = [

{name: "Acton Town", lines: "District, Piccadilly", zones: "3", image: require("./images/ActonTown.jpg")},
{name: "Aldgate", lines: "Metropolitan, Circle", zones: "1", image: require("./images/Aldgate.jpg")},
{name: "Aldgate East", lines: "Hammersmith & City, District", zones: "1", image: require("./images/AldgateEast.jpg")},
{name: "Alperton", lines: "Piccadilly", zones: "4", image: require("./images/Alperton.jpg")},
{name: "Amersham", lines: "Metropolitan", zones: "9", image: require("./images/Amersham.jpg")},
{name: "Angel", lines: "Northern", zones: "1", image: require("./images/Angel.jpg")},
{name: "Archway", lines: "Northern", zones: "2 & 3", image: require("./images/Archway.jpg")},
{name: "Arnos Grove", lines: "Piccadilly", zones: "4", image: require("./images/ArnosGrove.jpg")},
{name: "Arsenal", lines: "Piccadilly", zones: "2", image: require("./images/Arsenal.jpg")},
{name: "Baker Street", lines: "Metropolitan, Bakerloo, Circle, Jubilee, Hammersmith & City", zones: "1", image: require("./images/BakerStreet.jpg")},
{name: "Balham", lines: "Northern", zones: "3", image: require("./images/Balham.jpg")},
{name: "Bank", lines: "Waterloo & City, Northern, Central", zones: "1", image: require("./images/Bank.jpg")},
{name: "Barbican", lines: "Metropolitan, Circle, Hammersmith & City", zones: "1", image: require("./images/Barbican.jpg")},
{name: "Barking", lines: "District, Hammersmith & City", zones: "4", image: require("./images/Barking.jpg")},
{name: "Barkingside", lines: "Central", zones: "4", image: require("./images/Barkingside.jpg")},
{name: "Barons Court", lines: "District, Piccadilly", zones: "2", image: require("./images/BaronsCourt.jpg")},
{name: "Bayswater", lines: "District, Circle", zones: "1", image: require("./images/Bayswater.jpg")},
{name: "Becontree", lines: "District", zones: "5", image: require("./images/Becontree.jpg")},
{name: "Belsize Park", lines: "Northern", zones: "2", image: require("./images/BelsizePark.jpg")},
{name: "Bermondsey", lines: "Jubilee", zones: "2", image: require("./images/Bermondsey.jpg")},
{name: "Bethnal Green", lines: "Central", zones: "2", image: require("./images/BethnalGreen.jpg")},
{name: "Blackfriars", lines: "District, Circle", zones: "1", image: require("./images/Blackfriars.jpg")},
{name: "Blackhorse Road", lines: "Victoria", zones: "3", image: require("./images/BlackhorseRoad.jpg")},
{name: "Bond Street", lines: "Central, Jubilee", zones: "1", image: require("./images/BondStreet.jpg")},
{name: "Borough", lines: "Northern", zones: "1", image: require("./images/Borough.jpg")},
{name: "Boston Manor", lines: "Piccadilly", zones: "4", image: require("./images/BostonManor.jpg")},
{name: "Bounds Green", lines: "Piccadilly", zones: "3 & 4", image: require("./images/BoundsGreen.jpg")},
{name: "Bow Road", lines: "District, Hammersmith & City", zones: "2", image: require("./images/BowRoad.jpg")},
{name: "Brent Cross", lines: "Northern", zones: "3", image: require("./images/BrentCross.jpg")},
{name: "Brixton", lines: "Victoria", zones: "2", image: require("./images/Brixton.jpg")},
{name: "Bromley-by-Bow", lines: "District, Hammersmith & City", zones: "2 & 3", image: require("./images/Bromley-by-Bow.jpg")},
{name: "Buckhurst Hill", lines: "Central", zones: "5", image: require("./images/BuckhurstHill.jpg")},
{name: "Burnt Oak", lines: "Northern", zones: "4", image: require("./images/BurntOak.jpg")},
{name: "Caledonian Road", lines: "Piccadilly", zones: "2", image: require("./images/CaledonianRoad.jpg")},
{name: "Camden Town", lines: "Northern", zones: "2", image: require("./images/CamdenTown.jpg")},
{name: "Canada Water", lines: "Jubilee", zones: "2", image: require("./images/CanadaWater.jpg")},
{name: "Canary Wharf", lines: "Jubilee", zones: "2", image: require("./images/CanaryWharf.jpg")},
{name: "Canning Town", lines: "Jubilee", zones: "2 & 3", image: require("./images/CanningTown.jpg")},
{name: "Cannon Street", lines: "District, Circle", zones: "1", image: require("./images/CannonStreet.jpg")},
{name: "Canons Park", lines: "Jubilee", zones: "5", image: require("./images/CanonsPark.jpg")},
{name: "Chalfont & Latimer", lines: "Metropolitan", zones: "8", image: require("./images/Chalfont&Latimer.jpg")},
{name: "Chalk Farm", lines: "Northern", zones: "2", image: require("./images/ChalkFarm.jpg")},
/*{name: "Chancery Lane", lines: "Central", zones: "1", image: require("./images/ChanceryLane.jpg")},
{name: "Charing Cross", lines: "Bakerloo, Northern", zones: "1", image: require("./images/CharingCross.jpg")},
{name: "Chesham", lines: "Metropolitan", zones: "9", image: require("./images/Chesham.jpg")},
{name: "Chigwell", lines: "Central", zones: "4", image: require("./images/Chigwell.jpg")},
{name: "Chiswick Park", lines: "District", zones: "3", image: require("./images/ChiswickPark.jpg")},
{name: "Chorleywood", lines: "Metropolitan", zones: "7", image: require("./images/Chorleywood.jpg")},
{name: "Clapham Common", lines: "Northern", zones: "2", image: require("./images/ClaphamCommon.jpg")},
{name: "Clapham North", lines: "Northern", zones: "2", image: require("./images/ClaphamNorth.jpg")},
{name: "Clapham South", lines: "Northern", zones: "2 & 3", image: require("./images/ClaphamSouth.jpg")},
{name: "Cockfosters", lines: "Piccadilly", zones: "5", image: require("./images/Cockfosters.jpg")},
{name: "Colindale", lines: "Northern", zones: "4", image: require("./images/Colindale.jpg")},
{name: "Colliers Wood", lines: "Northern", zones: "3", image: require("./images/ColliersWood.jpg")},
{name: "Covent Garden", lines: "Piccadilly", zones: "1", image: require("./images/CoventGarden.jpg")},
{name: "Croxley", lines: "Metropolitan", zones: "7", image: require("./images/Croxley.jpg")},
{name: "Dagenham East", lines: "District", zones: "5", image: require("./images/DagenhamEast.jpg")},
{name: "Dagenham Heathway", lines: "District", zones: "5", image: require("./images/DagenhamHeathway.jpg")},
{name: "Debden", lines: "Central", zones: "6", image: require("./images/Debden.jpg")},
{name: "Dollis Hill", lines: "Jubilee", zones: "3", image: require("./images/DollisHill.jpg")},
{name: "Ealing Broadway", lines: "District, Central", zones: "3", image: require("./images/EalingBroadway.jpg")},
{name: "Ealing Common", lines: "District, Piccadilly", zones: "3", image: require("./images/EalingCommon.jpg")},
{name: "Earl's Court", lines: "District, Piccadilly", zones: "1 & 2", image: require("./images/Earl'sCourt.jpg")},
{name: "East Acton", lines: "Central", zones: "2", image: require("./images/EastActon.jpg")},
{name: "East Finchley", lines: "Northern", zones: "3", image: require("./images/EastFinchley.jpg")},
{name: "East Ham", lines: "District, Hammersmith & City", zones: "3 & 4", image: require("./images/EastHam.jpg")},
{name: "Eastcote", lines: "Metropolitan, Piccadilly", zones: "5", image: require("./images/Eastcote.jpg")},
{name: "Edgware", lines: "Northern", zones: "5", image: require("./images/Edgware.jpg")},
{name: "Edgware Road", lines: "Bakerloo", zones: "1", image: require("./images/EdgwareRoad(Bakerlooline).png")},
{name: "Edgware Road", lines: "Hammersmith & City, District, Circle", zones: "1", image: require("./images/EdgwareRoad.jpg")},
{name: "Elephant & Castle", lines: "Northern, Bakerloo", zones: "1 & 2", image: require("./images/Elephant&Castle.jpg")},
{name: "Elm Park", lines: "District", zones: "6", image: require("./images/ElmPark.jpg")},
{name: "Embankment", lines: "District, Bakerloo, Northern, Circle", zones: "1", image: require("./images/Embankment.jpg")},
{name: "Epping", lines: "Central", zones: "6", image: require("./images/Epping.jpg")},
{name: "Euston", lines: "Northern, Victoria", zones: "1", image: require("./images/Euston.jpg")},
{name: "Euston Square", lines: "Metropolitan, Circle, Hammersmith & City", zones: "1", image: require("./images/EustonSquare.jpg")},
{name: "Fairlop", lines: "Central", zones: "4", image: require("./images/Fairlop.jpg")},
{name: "Farringdon", lines: "Metropolitan, Circle, Hammersmith & City", zones: "1", image: require("./images/Farringdon.jpg")},
{name: "Finchley Central", lines: "Northern", zones: "4", image: require("./images/FinchleyCentral.jpg")},
{name: "Finchley Road", lines: "Metropolitan, Jubilee", zones: "2", image: require("./images/FinchleyRoad.jpg")},
{name: "Finsbury Park", lines: "Piccadilly, Victoria", zones: "2", image: require("./images/FinsburyPark.jpg")},
{name: "Fulham Broadway", lines: "District", zones: "2", image: require("./images/FulhamBroadway.jpg")},
{name: "Gants Hill", lines: "Central", zones: "4", image: require("./images/GantsHill.jpg")},
{name: "Gloucester Road", lines: "District, Piccadilly, Circle", zones: "1", image: require("./images/GloucesterRoad.jpg")},
{name: "Golders Green", lines: "Northern", zones: "3", image: require("./images/GoldersGreen.jpg")},
{name: "Goldhawk Road", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/GoldhawkRoad.jpg")},
{name: "Goodge Street", lines: "Northern", zones: "1", image: require("./images/GoodgeStreet.jpg")},
{name: "Grange Hill", lines: "Central", zones: "4", image: require("./images/GrangeHill.jpg")},
{name: "Great Portland Street", lines: "Metropolitan, Circle, Hammersmith & City", zones: "1", image: require("./images/GreatPortlandStreet.jpg")},
{name: "Green Park", lines: "Central", zones: "1", image: require("./images/GreenPark.jpg")},
{name: "Greenford", lines: "Piccadilly, Victoria, Jubilee", zones: "4", image: require("./images/Greenford.jpg")},
{name: "Gunnersbury", lines: "District", zones: "3", image: require("./images/Gunnersbury.jpg")},
{name: "Hainault", lines: "Central", zones: "4", image: require("./images/Hainault.jpg")},
{name: "Hammersmith", lines: "District, Piccadilly", zones: "2", image: require("./images/Hammersmith.jpg")},
{name: "Hammersmith", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/Hammersmith.jpg")},
{name: "Hampstead", lines: "Northern", zones: "2 & 3", image: require("./images/Hampstead.jpg")},
{name: "Hanger Lane", lines: "Central", zones: "3", image: require("./images/HangerLane.jpg")},
{name: "Harlesden", lines: "Bakerloo", zones: "3", image: require("./images/Harlesden.jpg")},
{name: "Harrow & Wealdstone", lines: "Bakerloo", zones: "5", image: require("./images/Harrow&Wealdstone.jpg")},
{name: "Harrow-on-the-Hill", lines: "Metropolitan", zones: "5", image: require("./images/Harrow-on-the-Hill.jpg")},
{name: "Hatton Cross", lines: "Piccadilly", zones: "5 & 6", image: require("./images/HattonCross.jpg")},
{name: "Heathrow Terminal 4", lines: "Piccadilly", zones: "6", image: require("./images/HeathrowTerminal4.jpg")},
{name: "Heathrow Terminal 5", lines: "Piccadilly", zones: "6", image: require("./images/HeathrowTerminal5.jpg")},
{name: "Heathrow Terminals 2 & 3", lines: "Piccadilly", zones: "6", image: require("./images/HeathrowTerminals2&3.jpg")},
{name: "Hendon Central", lines: "Northern", zones: "3 & 4", image: require("./images/HendonCentral.jpg")},
{name: "High Barnet", lines: "Northern", zones: "5", image: require("./images/HighBarnet.jpg")},
{name: "High Street Kensington", lines: "Victoria", zones: "1", image: require("./images/HighStreetKensington.jpg")},
{name: "Highbury & Islington", lines: "Northern", zones: "2", image: require("./images/Highbury&Islington.jpg")},
{name: "Highgate", lines: "District, Circle", zones: "3", image: require("./images/Highgate.jpg")},
{name: "Hillingdon", lines: "Metropolitan, Piccadilly", zones: "6", image: require("./images/Hillingdon.jpg")},
{name: "Holborn", lines: "Central, Piccadilly", zones: "1", image: require("./images/Holborn.jpg")},
{name: "Holland Park", lines: "Central", zones: "2", image: require("./images/HollandPark.jpg")},
{name: "Holloway Road", lines: "Piccadilly", zones: "2", image: require("./images/HollowayRoad.jpg")},
{name: "Hornchurch", lines: "District", zones: "6", image: require("./images/Hornchurch.jpg")},
{name: "Hounslow Central", lines: "Piccadilly", zones: "4", image: require("./images/HounslowCentral.jpg")},
{name: "Hounslow East", lines: "Piccadilly", zones: "4", image: require("./images/HounslowEast.jpg")},
{name: "Hounslow West", lines: "Piccadilly", zones: "5", image: require("./images/HounslowWest.jpg")},
{name: "Hyde Park Corner", lines: "Piccadilly", zones: "1", image: require("./images/HydeParkCorner.jpg")},
{name: "Ickenham", lines: "Metropolitan, Piccadilly", zones: "6", image: require("./images/Ickenham.jpg")},
{name: "Kennington", lines: "Northern", zones: "2", image: require("./images/Kennington.jpg")},
{name: "Kensal Green", lines: "Bakerloo", zones: "2", image: require("./images/KensalGreen.jpg")},
{name: "Kensington (Olympia)", lines: "District", zones: "2", image: require("./images/Kensington(Olympia).jpg")},
{name: "Kentish Town", lines: "Northern", zones: "2", image: require("./images/KentishTown.jpg")},
{name: "Kenton", lines: "Bakerloo", zones: "4", image: require("./images/Kenton.jpg")},
{name: "Kew Gardens", lines: "District", zones: "3 & 4", image: require("./images/KewGardens.jpg")},
{name: "Kilburn", lines: "Jubilee", zones: "2", image: require("./images/Kilburn.jpg")},
{name: "Kilburn Park", lines: "Bakerloo", zones: "2", image: require("./images/KilburnPark.jpg")},
{name: "King's Cross St. Pancras", lines: "Jubilee", zones: "1", image: require("./images/King'sCrossSt.Pancras.jpg")},
{name: "Kingsbury", lines: "Metropolitan, Northern, Piccadilly, Circle, Victoria, Hammersmith & City", zones: "4", image: require("./images/Kingsbury.jpg")},
{name: "Knightsbridge", lines: "Piccadilly", zones: "1", image: require("./images/Knightsbridge.jpg")},
{name: "Ladbroke Grove", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/LadbrokeGrove.jpg")},
{name: "Lambeth North", lines: "Bakerloo", zones: "1", image: require("./images/LambethNorth.jpg")},
{name: "Lancaster Gate", lines: "Central", zones: "1", image: require("./images/LancasterGate.jpg")},
{name: "Latimer Road", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/LatimerRoad.jpg")},
{name: "Leicester Square", lines: "Piccadilly, Northern", zones: "1", image: require("./images/LeicesterSquare.jpg")},
{name: "Leyton", lines: "Central", zones: "3", image: require("./images/Leyton.jpg")},
{name: "Leytonstone", lines: "Central", zones: "3 & 4", image: require("./images/Leytonstone.jpg")},
{name: "Liverpool Street", lines: "Metropolitan, Central, Circle, Hammersmith & City", zones: "1", image: require("./images/LiverpoolStreet.jpg")},
{name: "London Bridge", lines: "Northern, Jubilee", zones: "1", image: require("./images/LondonBridge.jpg")},
{name: "Loughton", lines: "Central", zones: "6", image: require("./images/Loughton.jpg")},
{name: "Maida Vale", lines: "Bakerloo", zones: "2", image: require("./images/MaidaVale.jpg")},
{name: "Manor House", lines: "Piccadilly", zones: "2 & 3", image: require("./images/ManorHouse.jpg")},
{name: "Mansion House", lines: "District, Circle", zones: "1", image: require("./images/MansionHouse.jpg")},
{name: "Marble Arch", lines: "Central", zones: "1", image: require("./images/MarbleArch.jpg")},
{name: "Marylebone", lines: "Bakerloo", zones: "1", image: require("./images/Marylebone.jpg")},
{name: "Mile End", lines: "District, Hammersmith & City, Central", zones: "2", image: require("./images/MileEnd.jpg")},
{name: "Mill Hill East", lines: "Northern", zones: "4", image: require("./images/MillHillEast.jpg")},
{name: "Monument", lines: "District, Circle", zones: "1", image: require("./images/Monument.jpg")},
{name: "Moor Park", lines: "Metropolitan, Northern, Circle, Hammersmith & City", zones: "6 & 7", image: require("./images/MoorPark.jpg")},
{name: "Moorgate", lines: "Metropolitan", zones: "1", image: require("./images/Moorgate.jpg")},
{name: "Morden", lines: "Northern", zones: "4", image: require("./images/Morden.jpg")},
{name: "Mornington Crescent", lines: "Northern", zones: "2", image: require("./images/MorningtonCrescent.jpg")},
{name: "Neasden", lines: "Jubilee", zones: "3", image: require("./images/Neasden.jpg")},
{name: "Newbury Park", lines: "Central", zones: "4", image: require("./images/NewburyPark.jpg")},
{name: "North Acton", lines: "Central", zones: "2 & 3", image: require("./images/NorthActon.jpg")},
{name: "North Ealing", lines: "Piccadilly", zones: "3", image: require("./images/NorthEaling.jpg")},
{name: "North Greenwich", lines: "Jubilee", zones: "2 & 3", image: require("./images/NorthGreenwich.jpg")},
{name: "North Harrow", lines: "Metropolitan", zones: "5", image: require("./images/NorthHarrow.jpg")},
{name: "North Wembley", lines: "Bakerloo", zones: "4", image: require("./images/NorthWembley.jpg")},
{name: "Northfields", lines: "Piccadilly", zones: "3", image: require("./images/Northfields.jpg")},
{name: "Northolt", lines: "Central", zones: "5", image: require("./images/Northolt.jpg")},
{name: "Northwick Park", lines: "Metropolitan", zones: "4", image: require("./images/NorthwickPark.jpg")},
{name: "Northwood", lines: "Metropolitan", zones: "6", image: require("./images/Northwood.jpg")},
{name: "Northwood Hills", lines: "Metropolitan", zones: "6", image: require("./images/NorthwoodHills.jpg")},
{name: "Notting Hill Gate", lines: "District, Central, Circle", zones: "1 & 2", image: require("./images/NottingHillGate.jpg")},
{name: "Oakwood", lines: "Piccadilly", zones: "5", image: require("./images/Oakwood.jpg")},
{name: "Old Street", lines: "Northern", zones: "1", image: require("./images/OldStreet.jpg")},
{name: "Osterley", lines: "Piccadilly", zones: "4", image: require("./images/Osterley.jpg")},
{name: "Oval", lines: "Northern", zones: "2", image: require("./images/Oval.jpg")},
{name: "Oxford Circus", lines: "Central, Bakerloo, Victoria", zones: "1", image: require("./images/OxfordCircus.jpg")},
{name: "Paddington", lines: "District, Circle, Bakerloo", zones: "1", image: require("./images/Paddington.jpg")},
{name: "Paddington", lines: "Hammersmith & City, Circle", zones: "1", image: require("./images/Paddington.jpg")},
{name: "Park Royal", lines: "Piccadilly", zones: "3", image: require("./images/ParkRoyal.jpg")},
{name: "Parsons Green", lines: "District", zones: "2", image: require("./images/ParsonsGreen.jpg")},
{name: "Perivale", lines: "Central", zones: "4", image: require("./images/Perivale.jpg")},
{name: "Piccadilly Circus", lines: "Bakerloo, Piccadilly", zones: "1", image: require("./images/PiccadillyCircus.png")},
{name: "Pimlico", lines: "Victoria", zones: "1", image: require("./images/Pimlico.jpg")},
{name: "Pinner", lines: "Metropolitan", zones: "5", image: require("./images/Pinner.jpg")},
{name: "Plaistow", lines: "District, Hammersmith & City", zones: "3", image: require("./images/Plaistow.jpg")},
{name: "Preston Road", lines: "Metropolitan", zones: "4", image: require("./images/PrestonRoad.jpg")},
{name: "Putney Bridge", lines: "District", zones: "2", image: require("./images/PutneyBridge.jpg")},
{name: "Queen's Park", lines: "Bakerloo", zones: "2", image: require("./images/Queen'sPark.jpg")},
{name: "Queensbury", lines: "Jubilee", zones: "4", image: require("./images/Queensbury.jpg")},
{name: "Queensway", lines: "Central", zones: "1", image: require("./images/Queensway.jpg")},
{name: "Ravenscourt Park", lines: "District", zones: "2", image: require("./images/RavenscourtPark.jpg")},
{name: "Rayners Lane", lines: "Metropolitan, Piccadilly", zones: "5", image: require("./images/RaynersLane.jpg")},
{name: "Redbridge", lines: "Central", zones: "4", image: require("./images/Redbridge.jpg")},
{name: "Regent's Park", lines: "Bakerloo", zones: "1", image: require("./images/Regent'sPark.jpg")},
{name: "Richmond", lines: "District", zones: "4", image: require("./images/Richmond.jpg")},
{name: "Rickmansworth", lines: "Metropolitan", zones: "7", image: require("./images/Rickmansworth.jpg")},
{name: "Roding Valley", lines: "Central", zones: "4", image: require("./images/RodingValley.jpg")},
{name: "Royal Oak", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/RoyalOak.jpg")},
{name: "Ruislip", lines: "Metropolitan, Piccadilly", zones: "6", image: require("./images/Ruislip.jpg")},
{name: "Ruislip Gardens", lines: "Central", zones: "5", image: require("./images/RuislipGardens.jpg")},
{name: "Ruislip Manor", lines: "Metropolitan, Piccadilly", zones: "6", image: require("./images/RuislipManor.jpg")},
{name: "Russell Square", lines: "Piccadilly", zones: "1", image: require("./images/RussellSquare.jpg")},
{name: "Seven Sisters", lines: "District, Circle", zones: "3", image: require("./images/SevenSisters.jpg")},
{name: "Shepherd's Bush", lines: "Jubilee", zones: "2", image: require("./images/Shepherd'sBush.jpg")},
{name: "Shepherd's Bush Market", lines: "Central", zones: "2", image: require("./images/Shepherd'sBushMarket.jpg")},
{name: "Sloane Square", lines: "Victoria", zones: "1", image: require("./images/SloaneSquare.jpg")},
{name: "Snaresbrook", lines: "Central", zones: "4", image: require("./images/Snaresbrook.jpg")},
{name: "South Ealing", lines: "Hammersmith & City, Circle", zones: "3", image: require("./images/SouthEaling.jpg")},
{name: "South Harrow", lines: "District, Circle", zones: "5", image: require("./images/SouthHarrow.jpg")},
{name: "South Kensington", lines: "Central", zones: "1", image: require("./images/SouthKensington.jpg")},
{name: "South Kenton", lines: "Piccadilly", zones: "4", image: require("./images/SouthKenton.jpg")},
{name: "South Ruislip", lines: "Piccadilly", zones: "5", image: require("./images/SouthRuislip.jpg")},
{name: "South Wimbledon", lines: "District, Piccadilly, Circle", zones: "3 & 4", image: require("./images/SouthWimbledon.jpg")},
{name: "South Woodford", lines: "Bakerloo", zones: "4", image: require("./images/SouthWoodford.jpg")},
{name: "Southfields", lines: "Central", zones: "3", image: require("./images/Southfields.jpg")},
{name: "Southgate", lines: "Northern", zones: "4", image: require("./images/Southgate.jpg")},
{name: "Southwark", lines: "Central", zones: "1", image: require("./images/Southwark.jpg")},
{name: "St. James's Park", lines: "District", zones: "1", image: require("./images/St.James'sPark.jpg")},
{name: "St. John's Wood", lines: "Piccadilly", zones: "2", image: require("./images/St.John'sWood.jpg")},
{name: "St. Paul's", lines: "Jubilee", zones: "1", image: require("./images/St.Paul's.jpg")},
{name: "Stamford Brook", lines: "District", zones: "2", image: require("./images/StamfordBrook.jpg")},
{name: "Stanmore", lines: "Jubilee", zones: "5", image: require("./images/Stanmore.jpg")},
{name: "Stepney Green", lines: "District, Hammersmith & City", zones: "2", image: require("./images/StepneyGreen.jpg")},
{name: "Stockwell", lines: "Northern, Victoria", zones: "2", image: require("./images/Stockwell.jpg")},
{name: "Stonebridge Park", lines: "Bakerloo", zones: "3", image: require("./images/StonebridgePark.jpg")},
{name: "Stratford", lines: "Central, Jubilee", zones: "2 & 3", image: require("./images/Stratford.jpg")},
{name: "Sudbury Hill", lines: "Piccadilly", zones: "4", image: require("./images/SudburyHill.jpg")},
{name: "Sudbury Town", lines: "Piccadilly", zones: "4", image: require("./images/SudburyTown.jpg")},
{name: "Swiss Cottage", lines: "Jubilee", zones: "2", image: require("./images/SwissCottage.jpg")},
{name: "Temple", lines: "District, Circle", zones: "1", image: require("./images/Temple.jpg")},
{name: "Theydon Bois", lines: "Central", zones: "6", image: require("./images/TheydonBois.jpg")},
{name: "Tooting Bec", lines: "Northern", zones: "3", image: require("./images/TootingBec.jpg")},
{name: "Tooting Broadway", lines: "Northern", zones: "3", image: require("./images/TootingBroadway.jpg")},
{name: "Tottenham Court Road", lines: "Central, Northern", zones: "1", image: require("./images/TottenhamCourtRoad.png")},
{name: "Tottenham Hale", lines: "Victoria", zones: "3", image: require("./images/TottenhamHale.jpg")},
{name: "Totteridge & Whetstone", lines: "Northern", zones: "4", image: require("./images/Totteridge&Whetstone.jpg")},
{name: "Tower Hill", lines: "District, Circle", zones: "1", image: require("./images/TowerHill.jpg")},
{name: "Tufnell Park", lines: "Northern", zones: "2", image: require("./images/TufnellPark.jpg")},
{name: "Turnham Green", lines: "District, Piccadilly", zones: "2 & 3", image: require("./images/TurnhamGreen.jpg")},
{name: "Turnpike Lane", lines: "Piccadilly", zones: "3", image: require("./images/TurnpikeLane.jpg")},
{name: "Upminster", lines: "District", zones: "6", image: require("./images/Upminster.jpg")},
{name: "Upminster Bridge", lines: "District", zones: "6", image: require("./images/UpminsterBridge.jpg")},
{name: "Upney", lines: "District", zones: "4", image: require("./images/Upney.jpg")},
{name: "Upton Park", lines: "District, Hammersmith & City", zones: "3", image: require("./images/UptonPark.jpg")},
{name: "Uxbridge", lines: "Metropolitan, Piccadilly", zones: "6", image: require("./images/Uxbridge.jpg")},
{name: "Vauxhall", lines: "Victoria", zones: "1 & 2", image: require("./images/Vauxhall.jpg")},
{name: "Victoria", lines: "District, Circle, Victoria", zones: "1", image: require("./images/Victoria.jpg")},
{name: "Walthamstow Central", lines: "Victoria", zones: "3", image: require("./images/WalthamstowCentral.jpg")},
{name: "Wanstead", lines: "Central", zones: "4", image: require("./images/Wanstead.jpg")},
{name: "Warren Street", lines: "Northern, Victoria", zones: "1", image: require("./images/WarrenStreet.jpg")},
{name: "Warwick Avenue", lines: "Bakerloo", zones: "2", image: require("./images/WarwickAvenue.jpg")},
{name: "Waterloo", lines: "Waterloo & City, Bakerloo, Northern, Jubilee", zones: "1", image: require("./images/Waterloo.jpg")},
{name: "Watford", lines: "Metropolitan", zones: "7", image: require("./images/Watford.jpg")},
{name: "Wembley Central", lines: "Bakerloo", zones: "4", image: require("./images/WembleyCentral.jpg")},
{name: "Wembley Park", lines: "Metropolitan, Jubilee", zones: "4", image: require("./images/WembleyPark.jpg")},
{name: "West Acton", lines: "Central", zones: "3", image: require("./images/WestActon.jpg")},
{name: "West Brompton", lines: "District", zones: "2", image: require("./images/WestBrompton.jpg")},
{name: "West Finchley", lines: "Northern", zones: "4", image: require("./images/WestFinchley.jpg")},
{name: "West Ham", lines: "District, Hammersmith & City, Jubilee", zones: "2 & 3", image: require("./images/WestHam.jpg")},
{name: "West Hampstead", lines: "Jubilee", zones: "2", image: require("./images/WestHampstead.jpg")},
{name: "West Harrow", lines: "Metropolitan", zones: "5", image: require("./images/WestHarrow.jpg")},
{name: "West Kensington", lines: "District", zones: "2", image: require("./images/WestKensington.jpg")},
{name: "West Ruislip", lines: "Central", zones: "6", image: require("./images/WestRuislip.jpg")},
{name: "Westbourne Park", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/WestbournePark.jpg")},
{name: "Westminster", lines: "District, Circle, Jubilee", zones: "1", image: require("./images/Westminster.jpg")},
{name: "White City", lines: "Central", zones: "2", image: require("./images/WhiteCity.jpg")},
{name: "Whitechapel", lines: "District, Hammersmith & City", zones: "2", image: require("./images/Whitechapel.jpg")},
{name: "Willesden Green", lines: "Jubilee", zones: "2 & 3", image: require("./images/WillesdenGreen.jpg")},
{name: "Willesden Junction", lines: "Bakerloo", zones: "2 & 3", image: require("./images/WillesdenJunction.jpg")},
{name: "Wimbledon", lines: "District", zones: "3", image: require("./images/Wimbledon.jpg")},
{name: "Wimbledon Park", lines: "District", zones: "3", image: require("./images/WimbledonPark.jpg")},
{name: "Wood Green", lines: "Piccadilly", zones: "3", image: require("./images/WoodGreen.jpg")},
{name: "Wood Lane", lines: "Hammersmith & City, Circle", zones: "2", image: require("./images/WoodLane.jpg")},
{name: "Woodford", lines: "Central", zones: "4", image: require("./images/Woodford.jpg")},
{name: "Woodside Park", lines: "Northern", zones: "4", image: require("./images/WoodsidePark.jpg")},
*/
];